FROM node:10
WORKDIR /usr/src/app
COPY src ./src/
COPY dist ./dist/
COPY *.json ./
COPY *.env ./
RUN ls -a
RUN npm install -g typescript
RUN npm install socket.io
RUN npm install @types/socket.io
RUN npm i ts-node
RUN npm install dotenv
RUN npm install express
RUN npm install firebase-admin
RUN tsc -p src/server
RUN npm install
EXPOSE 8080
CMD node dist/server/server.js